defmodule No18Test do
  use ExUnit.Case
  doctest No18

  test "AAA usa cryptanalysis BCD" do
    assert No18.work("BCD") == "AAA"
  end

  test "ZZZZZZZZZZZZZZZZZZZZZZZZZZ usa cryptanalysis ABCDEFGHIJKLMNOPQRSTUVWXYZ" do
    assert No18.work("ABCDEFGHIJKLMNOPQRSTUVWXYZ") == "ZZZZZZZZZZZZZZZZZZZZZZZZZZ"
  end

  test "YXWVUTSRQPONMLKJIHGFEDCBAZYXWVUTSRQPONMLKJIHGFEDCBAZYXWVUTSRQPONMLKJIHGFEDCBAZYXWVUTSRQPONMLKJIHGFEDCBAZ usa cryptanalysis ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ" do
    assert No18.work("ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ") == "YXWVUTSRQPONMLKJIHGFEDCBAZYXWVUTSRQPONMLKJIHGFEDCBAZYXWVUTSRQPONMLKJIHGFEDCBAZYXWVUTSRQPONMLKJIHGFEDCBAZ"
  end
end
